-- AlterEnum
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'COO';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CMO';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';

-- AlterTable
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "designation" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "department" TEXT;
