/**
 * BRANDX — Business Insights Prompt Builder
 * PRIVACY-SAFE: Aggregated, anonymized shop metrics only. No customer PII.
 */

export interface AggregatedBusinessMetrics {
  businessName: string;
  category: string;
  city?: string;
  khata: {
    totalCustomers: number;
    debtorCustomersCount: number;
    totalOutstandingUdhaar: number;
    totalAdvanceJama: number;
  };
  invoices: {
    totalInvoices: number;
    totalRevenue: number;
    recentInvoicesCount30Days: number;
    recentRevenue30Days: number;
    unpaidInvoicesCount: number;
  };
  inventory: {
    totalProducts: number;
    lowStockCount: number;
    outOfStockCount: number;
  };
}

export function buildBusinessInsightsPrompt(metrics: AggregatedBusinessMetrics, language: string = 'hinglish'): string {
  return `You are BrandX AI Business Advisor.
Analyze the following aggregated performance metrics for the shopkeeper "${metrics.businessName}" (${metrics.category}, ${metrics.city || 'India'}).

IMPORTANT: All figures are high-level store totals. No customer names or personal phone numbers are included.

AGGREGATED METRICS:
1. Customer Khata & Udhaar Ledger:
   - Total Registered Customers: ${metrics.khata.totalCustomers}
   - Customers with Pending Udhaar: ${metrics.khata.debtorCustomersCount}
   - Total Pending Udhaar Amount: ₹${metrics.khata.totalOutstandingUdhaar.toLocaleString('en-IN')}
   - Total Advance Jama Amount: ₹${metrics.khata.totalAdvanceJama.toLocaleString('en-IN')}

2. Sales & Billing Invoices:
   - Total Invoices Generated: ${metrics.invoices.totalInvoices}
   - Total Invoiced Revenue: ₹${metrics.invoices.totalRevenue.toLocaleString('en-IN')}
   - Invoices in Last 30 Days: ${metrics.invoices.recentInvoicesCount30Days}
   - Revenue in Last 30 Days: ₹${metrics.invoices.recentRevenue30Days.toLocaleString('en-IN')}
   - Unpaid / Partially Paid Invoices: ${metrics.invoices.unpaidInvoicesCount}

3. Inventory & Stock:
   - Total Catalog Products: ${metrics.inventory.totalProducts}
   - Low-Stock Alert Items: ${metrics.inventory.lowStockCount}
   - Out-of-Stock Items: ${metrics.inventory.outOfStockCount}

Provide actionable, realistic business insights in ${language}.
Always phrase observations as AI-generated suggestions, not guaranteed financial audits.

Output format: Return ONLY pure, valid JSON with this exact schema:
{
  "summary": "1-2 sentence overall health summary of the shop",
  "khataInsights": "Observations on outstanding collection, recovery tips, and cashflow impact",
  "salesInsights": "Observations on invoice volume, recent 30-day velocity, and repeat business",
  "stockInsights": "Observations on inventory health, reordering urgency, and dead stock prevention",
  "actionableSuggestions": [
    "Practical suggestion 1 (e.g. send WhatsApp payment reminder to 3 largest udhar accounts)",
    "Practical suggestion 2 (e.g. restock fast moving items before festival weekend)",
    "Practical suggestion 3"
  ],
  "disclaimer": "These insights are generated by BrandX Biz AI based on current aggregated shop records to assist your daily decisions."
}`;
}
